### PR TITLE
ZNTA-2277 Failed to merge to jenkinsci/zanata-plugin master

### PR DESCRIPTION
**Pull request by definite**
https://zanata.atlassian.net/browse/ZNTA-2277

Check also https://github.com/zanata/zanata-jenkins-plugin/pull/3

---
This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/zanata-plugin/14)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 1 of 1 files at r1, 1 of 2 files at r2.
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 296 at r2](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/14#-KzRS2jW63732zw7WyTj:-KzRS2jW63732zw7WyTk:b-70276m) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/5b9e55f8f137eb5e9132fafe62ab39c77a0b488f/pom.xml#L296)):*
> ```XML
>                will pick up the argLine set by jacoco:prepare-agent. -->
>           <argLine>@{argLine}</argLine>
>           <excludedGroups>${exclude.test.group}</excludedGroups>
> ```

why remove this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/14)*

**Comment by definite** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 296 at r2](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/14#-KzRS2jW63732zw7WyTj:-KzRTgiXK7uHn-CzHasP:b-718tnv) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/5b9e55f8f137eb5e9132fafe62ab39c77a0b488f/pom.xml#L296)):*
> <excludedGroups>${exclude.test.group}</excludedGroups>

Must be my mistake.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/14)*

**Comment by huangp** [comment]
Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 67 at r3](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/14#-KzS3dyQd5oOb8Fnpc8f:-KzS3dyQd5oOb8Fnpc8g:bcup0za) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/5b9e55f8f137eb5e9132fafe62ab39c77a0b488f/pom.xml#L67)):*
> ```XML
>     <developerConnection>scm:git:git@github.com:jenkinsci/${project.artifactId}-plugin.git</developerConnection>
>     <url>http://github.com/jenkinsci/${project.artifactId}-plugin</url>
>     <tag>HEAD</tag>
> ```

There should be no changes in this file I think?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/14)*

**Comment by definite** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 67 at r3](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/14#-KzS3dyQd5oOb8Fnpc8f:-KzXQNNTb2sOJBJ3y83i:b-l7cfdo) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/5b9e55f8f137eb5e9132fafe62ab39c77a0b488f/pom.xml#L67)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

There should be no changes in this file I think?
</blockquote></details>

pom.xml restored

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/14)*

**Comment by huangp** [comment]
:lgtm: 

---

Reviewed 1 of 1 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/14#-:-KzaFvfJAwyq3UZsBnEK:bg7igkv)*

**Pull request merged**
