### PR TITLE
Review: readthedocs for zanata-plugin

### PR DESCRIPTION
**Pull request by ghost**
Grammatical changes to readthedocs as necessary
Please proofread still

---
This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/zanata-plugin/9)

### CODE REVIEW

**Comment by ghost** [comment]
@aeng @huangp please review my changes

**Comment by huangp** [comment]
Reviewed 4 of 7 files at r1.
Review status: 4 of 7 files reviewed at latest revision, 17 unresolved discussions, some commit checks broke.

---

*[docs/index.md, line 13 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-Kfsp-iVskQMLuEsQMcV:-Kfsp-iVskQMLuEsQMcW:bpseupj) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/8fda8edd9e1943e660916fb83d71bbe434560547/docs/index.md#L13)):*
> ```Markdown
> - pull translation from Zanata server
> - commit translation into SCM (currently only git is supported automatically. Other SCM will need to use scripting)
> - push the commit to remote SCM (using git publisher or equivalent)
> ```

This file is needed for readthedocs. See mkdocs.yml file.

---

*[docs/configuration/index.md, line 7 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-KfspIR7IdMJVnJquZOI:-KfspIR7IdMJVnJquZOJ:b-116thv) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/index.md#L7)):*
> ```Markdown
> - Register a Zanata account and [have a generated API key](http://docs.zanata.org/en/release/user-guide/account/account-settings/#client)
> - Create the project and version to use (configure your locales, permissions etc)
> - [Download the Zanata project version config](http://docs.zanata.org/en/release/client/configuration/), customize it if needed and check it into your SCM
> ```

Any reason to remove the link to Zanata help?

---

*[docs/configuration/index.md, line 37 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-KfspRL0-vxRzKKnoOGW:-KfspRL0-vxRzKKnoOGX:byzxgtn) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/index.md#L37)):*
> ```Markdown
> Then in the 'Build' section, you will have two options to push source to and/or pull translation from Zanata server.
> 
> 1. [Use the plugin as a build step](/configuration/build-step/zanata-sync.md)    
> ```

No need to add .md extension. Readthedocs will get that link right.

---

*[docs/configuration/index.md, line 38 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-Kfsp_2skqQCxiB3hKhk:-Kfsp_2t7OdIFg0q2im9:brhumzt) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/index.md#L38)):*
> ```Markdown
> 
> 1. [Use the plugin as a build step](/configuration/build-step/zanata-sync.md)    
> 2. [Install Zanata CLI on Jenkins node and use scripting to invoke it](/configuration/build-step/install-cli.md)
> ```

Same here.

---

*[docs/configuration/post-build.md, line 3 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-KfspbzXqV3_WkJtiuwM:-KfspbzXqV3_WkJtiuwN:b-4v198s) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/post-build.md#L3)):*
> ```Markdown
> For example, if using git SCM, choose Git Publisher in post build step.
> <figure>
> Git Publisher Configuration
> ```

This image is too small. I was wrapping it in a link so people can click on it to open the image (full screen). 

---

*[docs/configuration/build-step/install-cli.md, line 1 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-KfsppJ55QuYVkQGMumI:-KfsppJ6aoMF8Gf5FafQ:bbr8t43) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/build-step/install-cli.md#L1)):*
> ```Markdown
> _NOTE:_ You will need to install [Credentials Binding Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Credentials+Binding+Plugin) to use this option.
> ```

For some reason this won't display under readthedocs. It has to be under a h3 or something similar (readthedocs markdown is different from github markdown)

---

*[docs/configuration/build-step/install-cli.md, line 20 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-KfsqgTGkBsD1EsLliPI:-KfsqgTGkBsD1EsLliPJ:bczrpl2) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/build-step/install-cli.md#L20)):*
> ```Markdown
> 
> ##### Individual Job Configuration
> Under 'Build Environment' section:
> ```

Need a new line under it to render the list properly

---

*[docs/configuration/build-step/install-cli.md, line 25 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-KfsqMC5MPYShM09c6Ty:-KfsqMC5MPYShM09c6Tz:bf4q9j0) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/build-step/install-cli.md#L25)):*
> ```Markdown
>     - Select the CLI from the dropdown in 'Zanata CLI selection'
>     - Optionally check 'Convert #CLIName_HOME variables to the upper-case'
> - Check 'Use secret text(s) or file(s)' then
> ```

Any reason to remove the link?

---

*[docs/configuration/build-step/install-cli.md, line 37 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-KfsqAWvvEHJKJDR-G_9:-KfsqAWwi1Ic4pYYMaiG:b-ugew8m) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/build-step/install-cli.md#L37)):*
> ```Markdown
> 
> You can use it in two ways:
> 1. Add a build step such as 'Execute shell' and invoke Zanata CLI in it
> ```

Tried this. It will render two 1. (the second 2. is considered a new numbered list)

---

*[docs/configuration/build-step/zanata-sync-via-cli.md, line 10 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-KfsrOo0htYcGZ3laaaj:-KfsrOo0htYcGZ3laaak:bq0f4ux) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/build-step/zanata-sync-via-cli.md#L10)):*
> ```Markdown
> - Go to 'Manage Jenkins'
> - Go to 'Configure System'
> - Scroll down to find 'Zanata CLI script template'
> ```

It was named in lower case on the screen. Shao requested to change the name to something else that I haven't done yet.

---

*[docs/configuration/build-step/zanata-sync-via-cli.md, line 12 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-KfsrYn2zW5WQl1XRtpR:-KfsrYn3Wyeu6L1kZs2w:b-81xdjm) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/build-step/zanata-sync-via-cli.md#L12)):*
> ```Markdown
> - Scroll down to find 'Zanata CLI script template'
>     
> There are two fields under 'Zanata CLI script template'. Each of them 
> ```

Same here. It was named in lower case

---

*[docs/configuration/build-step/zanata-sync-via-cli.md, line 21 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-KfsrcK7SWLto2O_yeGC:-KfsrcK7SWLto2O_yeGD:b-f5qd3b) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/build-step/zanata-sync-via-cli.md#L21)):*
> ```Markdown
> - Zanata username to be provided in an environment variable 'ZANATA_USERNAME', 
> and zanata API key provided in environment variable 'ZANATA_APIKEY'.
> - Zanata-CLI is on PATH
> ```

the executable file name is in lowercase

---

*[docs/configuration/build-step/zanata-sync-via-cli.md, line 23 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-KfsrKxxfUjlr99DxWN0:-KfsrKxxfUjlr99DxWN1:b9du5ep) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/build-step/zanata-sync-via-cli.md#L23)):*
> ```Markdown
> - Zanata-CLI is on PATH
> 
> See [CLI installation](/configuration/build-step/install-cli.md) for how to install CLI and how to bind Zanata credentials to environment variables.
> ```

No need to have .md extension

---

*[docs/configuration/build-step/zanata-sync-via-cli.md, line 43 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-KfsqRz23f2AmU5Os3KD:-KfsqRz23f2AmU5Os3KE:b-2n72tk) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/build-step/zanata-sync-via-cli.md#L43)):*
> ```Markdown
> Example configuration:
> <figure>
> Example configuration
> ```

Same reason. I was trying to make the small image clickable so people can open it in full screen.

---

*[docs/configuration/build-step/zanata-sync.md, line 10 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-KfsqrX3UgVjADlxIUDj:-KfsqrX3UgVjADlxIUDk:b-6wgfi9) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/build-step/zanata-sync.md#L10)):*
> ```Markdown
> Once selected, you should see its configuration:
> <figure>
> Zanata Sync build step configuration
> ```

Same clickable image idea.

---

*[docs/configuration/build-step/zanata-sync.md, line 13 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-Kfsql0sbuwzNFowiJ4B:-Kfsql0sbuwzNFowiJ4C:b-1agwwi) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/build-step/zanata-sync.md#L13)):*
> ```Markdown
> </figure>
> 
> Here you can:
> ```

Need a newline under it to render the list properly

---

*[docs/configuration/build-step/zanata-sync.md, line 22 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-KfsrG63Lmk-7GZVYd3S:-KfsrG63Lmk-7GZVYd3T:b-4x0t1q) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/build-step/zanata-sync.md#L22)):*
> ```Markdown
> 
> If you have translation commits in your build, you may also want to [push 
> that back to the remote SCM repo](/configuration/post-build.md).
> ```

No need to have the .md extension

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9)*

**Comment by ghost** [comment]
Review status: 4 of 7 files reviewed at latest revision, 17 unresolved discussions, some commit checks broke.

---

*[docs/configuration/index.md, line 7 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-KfspIR7IdMJVnJquZOI:-KfsxIED5ho9C9Cktw3X:bsf45y1) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/index.md#L7)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Any reason to remove the link to Zanata help?
</blockquote></details>

Unsure how that happened, adding back.

---

*[docs/configuration/post-build.md, line 3 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-KfspbzXqV3_WkJtiuwM:-KfsxyE6J5w25YOQnTdW:baxrfc2) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/post-build.md#L3)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

This image is too small. I was wrapping it in a link so people can click on it to open the image (full screen). 
</blockquote></details>

Sorry, accidentally removed some code.

---

*[docs/configuration/build-step/install-cli.md, line 25 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-KfsqMC5MPYShM09c6Ty:-KfsyZIFitE90KQFpYFf:b8drc4q) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/a37c56884bb3123caf744eccf6da17faebe049b4/docs/configuration/build-step/install-cli.md#L25)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Any reason to remove the link?
</blockquote></details>

Accidental, sorry

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9)*

**Comment by huangp** [comment]
Reviewed 1 of 7 files at r1, 5 of 6 files at r2.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks broke.

---

*[docs/configuration/build-step/install-cli.md, line 62 at r2](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-Kft1eZ0VRN58P6eQ2CW:-Kft1eZ1spxBt5MrLmLv:bb0v7ey) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/79ee1a5048ea7611570a5e630d48eb4609d94950/docs/configuration/build-step/install-cli.md#L62)):*
> ```Markdown
> 
> ```
> 2. Choose another build step [Zanata Sync via CLI](/configuration/zanata-sync-via-cli.md)
> ```

This will still be rendered as 1. Basically you can't add stuff in between numbered list. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9)*

**Comment by huangp** [comment]
:lgtm: I will merge it

---

Review status: 4 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9#-:-Kft_OFIkkduu4YSrXO3:b2otarf)*

**Comment by huangp** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/9)*

**Pull request merged**
