### PR TITLE
Added Jenkinsfile for building

### PR DESCRIPTION
**Pull request by huangp**
- Jenkinsfile is the one we use internally
- Jenkinsfile_jenkinsci is the one supposed to be used on https://ci.jenkins.io/job/Plugins/ (pending approval and job creation)
- fixed findbugs and improved test coverage

---
This change is [Reviewable](https://reviewable.io/reviews/jenkinsci/zanata-plugin/4)

### CODE REVIEW

**Comment by seanf** [comment]
Why is the source branch `zanata/master`?

For future work on the jenkins plugin, I think it would be better to work in temporary zanata branches, which we can rebase if we need to, or work on multiple things in different branches.

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[Jenkinsfile, line 37 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4#-KeGh1_rSX1nqGHIAIEh:-KeGh1_rSX1nqGHIAIEi:b-v9de4j) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/97cab1afaa4084e72e1b13fed328fb51c67379dd/Jenkinsfile#L37)):*
> ```Groovy
>           info.printEnv()
>           def testReports = 'target/surefire-reports/TEST-*.xml'
>           def jarFiles = 'target/*.jar'
> ```

Is it worth archiving the jar file? It's just used to build the hpi, I assume?

---

*[Jenkinsfile, line 63 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4#-KeGeq66j4QGzBV8Go74:-KeGeq66j4QGzBV8Go75:b5w10fz) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/97cab1afaa4084e72e1b13fed328fb51c67379dd/Jenkinsfile#L63)):*
> ```Groovy
>   notify.failed()
>   junit allowEmptyResults: true,
>       keepLongStdio: true,
> ```

http://javadoc.jenkins-ci.org/junit/hudson/tasks/junit/JUnitParser.html#JUnitParser-boolean-boolean-

Having looked into it, this option is probably a waste of disk space. I'll get dchen to remove it from zanata-platform too.

---

*[Jenkinsfile, line 73 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4#-KeGd1ynesl2ibEpTQ4B:-KeGd1yoaRwGbY8R21YB:b5wkkv1) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/97cab1afaa4084e72e1b13fed328fb51c67379dd/Jenkinsfile#L73)):*
> ```Groovy
>   if (currentBuild.result != null) {
>     archive(
>         includes: '*/target/**/*.log,**/target/site/jacoco/**')
> ```

I know you copied this from zanata-platform, but on reflection, I don't think it makes sense to archive jacoco results if the tests have failed. 

Will the logs from the embedded Jenkins used in tests be picked up here, or will they be inside a container's filesystem?  In the case of Zanata, this is designed to pick up WildFly/EAP logs from failed Arquillian/Cargo tests. Perhaps these logs just go to stdout, to be archived by `junit` above?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4#-:-KeGgWkt2bCqtW5ZkIXw:b-9y7o8q)*

**Comment by huangp** [comment]
Yep future work will definitely be in feature branch. I am working on master because there is a job already on zanata-jenkins for master. It will probably create a new job if I have a PR/branch which also contain Jenkinsfile. Yesterday I was just trying to get the initial Jenkinsfile working so was working on master.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks broke.

---

*[Jenkinsfile, line 37 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4#-KeGh1_rSX1nqGHIAIEh:-KeGyO-7jmPf51dwXleY:b-896fix) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/97cab1afaa4084e72e1b13fed328fb51c67379dd/Jenkinsfile#L37)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Is it worth archiving the jar file? It's just used to build the hpi, I assume?
</blockquote></details>

Done.

---

*[Jenkinsfile, line 63 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4#-KeGeq66j4QGzBV8Go74:-KeGywZVgn6P5eSqZTjT:b-896fix) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/97cab1afaa4084e72e1b13fed328fb51c67379dd/Jenkinsfile#L63)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

http://javadoc.jenkins-ci.org/junit/hudson/tasks/junit/JUnitParser.html#JUnitParser-boolean-boolean-

Having looked into it, this option is probably a waste of disk space. I'll get dchen to remove it from zanata-platform too.
</blockquote></details>

Done.

---

*[Jenkinsfile, line 73 at r1](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4#-KeGd1ynesl2ibEpTQ4B:-KeGzP_dcWmW9bH-CF0Y:b-5jdn4t) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/97cab1afaa4084e72e1b13fed328fb51c67379dd/Jenkinsfile#L73)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

I know you copied this from zanata-platform, but on reflection, I don't think it makes sense to archive jacoco results if the tests have failed. 

Will the logs from the embedded Jenkins used in tests be picked up here, or will they be inside a container's filesystem?  In the case of Zanata, this is designed to pick up WildFly/EAP logs from failed Arquillian/Cargo tests. Perhaps these logs just go to stdout, to be archived by `junit` above?
</blockquote></details>

In fact I don't need this. This is for integration test phase and there is none here. I could just delete this function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4#-:-KeGxupEj_IAYzcMkfHZ:byy76dc)*

**Comment by seanf** [comment]
Okay. But note that the pipeline plugin (specifically the Organization Folder) should be able to pick up any branch containing a Jenkinsfile.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Jenkinsfile, line 50 at r2](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4#-KeH3U_5LZKZsNR1QXXU:-KeH3U_5LZKZsNR1QXXV:b-7xa6g6) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/5a9c68bfc56744dec1e46a996dad758dcf1d4c5a/Jenkinsfile#L50)):*
> ```Groovy
>           // notify if compile+unit test successful
>           notify.testResults(null)
>           archive "**/${hpiFiles},**/target/site/jacoco/**"
> ```

cc: @definite @aeng

Instead of archiving the raw jacoco.exec files, I think we can generate the report like this:

    step([$class: 'JacocoPublisher'])


Requires jacoco plugin 2.1.0+.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4#-:-KeH48WUJ1frnx_A-FJm:bghofx6)*

**Comment by huangp** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[Jenkinsfile, line 50 at r2](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4#-KeH3U_5LZKZsNR1QXXU:-KeHeeT7Tz7DaEVUAaTk:b-896fix) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/5a9c68bfc56744dec1e46a996dad758dcf1d4c5a/Jenkinsfile#L50)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

cc: @definite @aeng

Instead of archiving the raw jacoco.exec files, I think we can generate the report like this:

    step([$class: 'JacocoPublisher'])


Requires jacoco plugin 2.1.0+.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4)*

**Comment by seanf** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[Jenkinsfile, line 50 at r2](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4#-KeH3U_5LZKZsNR1QXXU:-KeH6a_PWKwQs4-pzApD:bw3vjbn) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/5a9c68bfc56744dec1e46a996dad758dcf1d4c5a/Jenkinsfile#L50)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry @huangp, I thought this was archiving jacoco.exec files, not jacoco reports. Once we get the JacocoPublisher working properly, we shouldn't need the maven's plugin's reports, but they'll come in handy until then.

For now, let's archive the report (again) and comment out the JacocoPublisher below.

---

*[Jenkinsfile, line 59 at r3](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4#-KeHfXggnc-jCGRYWyqj:-KeHfXggnc-jCGRYWyqk:bz80n2b) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/6fbbed78d09532089b5b1dbe560fd399e3b527d5/Jenkinsfile#L59)):*
> ```Groovy
>         stage('Stash') {
>           stash name: 'workspace', includes: '**'
>         }
> ```

There's no need to stash files unless you're going to unstash them later on a different node (eg to run integration tests on multiple platforms).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4)*

**Comment by huangp** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks broke.

---

*[Jenkinsfile, line 50 at r2](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4#-KeH3U_5LZKZsNR1QXXU:-KeHhCaEcVvOQxwV7N-F:b-896fix) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/5a9c68bfc56744dec1e46a996dad758dcf1d4c5a/Jenkinsfile#L50)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

Sorry @huangp, I thought this was archiving jacoco.exec files, not jacoco reports. Once we get the JacocoPublisher working properly, we shouldn't need the maven's plugin's reports, but they'll come in handy until then.

For now, let's archive the report (again) and comment out the JacocoPublisher below.
</blockquote></details>

Done.

---

*[Jenkinsfile, line 59 at r3](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4#-KeHfXggnc-jCGRYWyqj:-KeHgqPxk1KAZVQQH_vT:b-896fix) ([raw file](https://github.com/jenkinsci/zanata-plugin/blob/6fbbed78d09532089b5b1dbe560fd399e3b527d5/Jenkinsfile#L59)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary><blockquote>

There's no need to stash files unless you're going to unstash them later on a different node (eg to run integration tests on multiple platforms).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/jenkinsci/zanata-plugin/4#-:-KeHhVTdIk8EsSVfpqrn:bnfp4nl)*

**Pull request merged**
